### Get all animator
GET http://localhost:3001/animator

### Get animator by id
GET http://localhost:3001/animator/1

### Post a animator (json)
POST http://localhost:4000/animator
Accept: application/json
Content-type: application/json; charset=utf-8

    {
      "animator_firstname": "Justine",
      "animator_lastname": "The_Best",
      "animator_description": "fgsdlkjgsdflkj",
      "animator_image": "https://www.journaldugeek.com/content/uploads/2020/05/avatar.jpg"
    }

### Update a animator
PUT http://localhost:3001/animator/1
Accept: application/json
Content-Type: application/json

{
    "animator_firstname": "Jean23",
    "animator_lastname": "Jacques",
    "animator_description": "Animateur web",
    "animator_image": null
}

### Del animator by id
DELETE http://localhost:3001/animator/4

### get animator from program
GET http://localhost:3001/animator?program=2

### get animator from podcast
GET http://localhost:3001/animator?podcast=1