### Get all program
GET http://localhost:3001/program

### Get program by id
GET http://localhost:3001/program/2

### Post a program (json)
POST http://localhost:3001/program
Accept: application/json
Content-Type: application/json

{
      "program_title": "te7",
      "program_description": "",
      "program_image": null,
      "ro_category_category_id": 1,
      "ro_animator_animator_id": [1, 2]
}

### Update a program
PUT  http://localhost:3001/program/11
Content-Type: application/json

{
      "program_title": "Update",
      "program_description": "ddddddd",
      "program_image": null,
      "ro_category_category_id": 1,
      "ro_animator_animator_id": [3, 4]
}

###Delete a program
DELETE http://localhost:3001/program/4

### get all program from animator
GET http://localhost:3001/program?animator=1

### get all program from categorie
GET http://localhost:3001/program?categorie=2