### create a user
POST http://localhost:3001/signin
Accept: application/json
Content-Type: application/json

{
      "admin_user": "tutu",
      "admin_email": "tutu@tutu.tu",
      "admin_password": "tutu"
}